defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.0"

executor: KubernetesExecutor
fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
webserverSecretKey: "ShouldNotBeInProduction"

scheduler:
  replicas: 2

webserver:
  replicas: 2
  readinessProbe:
    initialDelaySeconds: 45
  livenessProbe:
    initialDelaySeconds: 60

statsd:
  uid: null

pgbouncer:
  uid: null

redis:
  uid: null

dags:
  persistence:
    enabled: false
  gitSync:
    uid: null
    enabled: true
    # repo: https://github.com/opendatahub-io-contrib/airflow-on-openshift.git
    # branch: main
    # subPath: dags

logs:
  persistence:
    enabled: false

flower:
  enabled: false

# ingress:
#   web:
#     enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
